language: python
python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    packages:
      - python3-pyicu
      - python-pyicu

install:
  - pip install codecov coveralls tox
script:
  - tox --
after_success:
  - coveralls
  - codecov
env:
  - TOXENV: py27-django111
  - TOXENV=py34-django111
  - TOXENV=py35-django111
  - TOXENV=py36-django111
  - TOXENV=pypy-django111

  - TOXENV=py34-django20
  - TOXENV=py35-django20
  - TOXENV=py36-django20

  - TOXENV=bare

  - TOXENV=isort
  - TOXENV=docs
