language: python
python:
  - "3.5"

services:
  - postgresql

addons:
  postgresql: "9.4"

install:
  - pip install codecov coveralls tox
script:
  - tox --
after_success:
  - coveralls
  - codecov
env:
  - TOXENV=py27-django18
  - TOXENV=py34-django18
  - TOXENV=py35-django18
  - TOXENV=pypy-django18

  - TOXENV=py27-django19
  - TOXENV=py34-django19
  - TOXENV=py35-django19
  - TOXENV=pypy-django19

  - TOXENV=py27-django110
  - TOXENV=py34-django110
  - TOXENV=py35-django110
  - TOXENV=pypy-django110

  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=py35-django111
  - TOXENV=pypy-django111
