# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobetta', '0007_remove_comment_msgid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationfile',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationfile',
            name='last_compiled',
            field=models.DateTimeField(null=True),
        ),
    ]
