# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobetta', '0009_auto_20170411_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobetta_editlogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobetta_messagecomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
