# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobetta', '0010_auto_20170421_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlog',
            name='msgid',
            field=models.TextField(),
        ),
    ]
