name: Continuous Integration (CI)

on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.6]
    steps:
      - run: echo "The CI was triggered! Youpiiiii!"
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Install tox
        run: pip install codecov coveralls tox
      - name: Run tox
        run: tox --
